  version: '3'

  tasks:
    # Build
    build:
      cmds:
        - go build -v -i ./...
    # Run
    run:
      cmds:
        - go run ./... --config=./config/local.yaml
    # Storage Up
    storage-up:
      cmds:
        - docker-compose up -d
    # Storage Down
    storage-down:
      cmds:
        - docker-compose down
    # Migration init Up
    mgr-up:
      cmds:
        - migrate -path migrations -database "postgresql://postgres:postgres@localhost:5432/people_db?sslmode=disable" -verbose up
    # Migration init Down
    mgr-down:
      cmds:
        - migrate -path migrations -database "postgresql://postgres:postgres@localhost:5432/people_db?sslmode=disable" -verbose down
    # Create DB
    createdb:
      cmds:
        - docker exec -it person-storage createdb --username=postgres --owner=postgres people_db
    # Drop DB
    dropdb:
      cmds:
        - docker exec -it person-storage dropdb people_db